"""100 张测试图 + 3 张验证图的人工内容标注（逐张目视，见 /tmp/csig_sheets/）。

字段：scene 主类 / light 光照 / dist 主体距离 / extra 附加标签
scene: city_far(远景城市天际线) building(单体建筑/幕墙) street(街景地面)
       vegetation(植被/花卉) water(水面) object(雕塑器物) signage(招牌文字为主) indoor(室内)
light: day / dusk / night
dist:  tele_far(长焦远景) mid(中景) close(近景/微距)
"""

L = {
 1:  ("city_far", "night", "tele_far", ["heritage_lit"]),
 2:  ("city_far", "night", "tele_far", []),
 3:  ("city_far", "night", "tele_far", []),
 4:  ("city_far", "night", "tele_far", []),
 5:  ("building", "night", "mid", ["facade"]),
 6:  ("building", "day", "mid", ["construction", "scaffold", "crane"]),
 7:  ("building", "day", "close", ["construction", "scaffold"]),
 8:  ("building", "day", "mid", ["text_sign", "storefront"]),
 9:  ("building", "day", "close", ["text_sign", "storefront"]),
 10: ("building", "day", "mid", ["heritage"]),
 11: ("building", "day", "mid", []),
 12: ("city_far", "day", "tele_far", ["water", "crane"]),
 13: ("vegetation", "day", "mid", ["blossom"]),
 14: ("city_far", "night", "tele_far", []),
 15: ("building", "night", "mid", ["lit_facade"]),
 16: ("building", "dusk", "mid", ["facade"]),
 17: ("vegetation", "night", "close", ["flower"]),
 18: ("signage", "night", "close", ["text_sign", "lit"]),
 19: ("street", "day", "close", ["vehicle", "text_sign"]),
 20: ("vegetation", "day", "mid", []),
 21: ("building", "day", "mid", ["construction", "crane"]),
 22: ("building", "day", "mid", ["construction", "crane"]),
 23: ("building", "day", "close", ["text_sign", "storefront"]),
 24: ("building", "day", "tele_far", ["haze"]),
 25: ("building", "day", "tele_far", ["haze"]),
 26: ("building", "day", "mid", ["construction", "crane"]),
 27: ("vegetation", "day", "mid", ["building"]),
 28: ("vegetation", "day", "tele_far", []),
 29: ("building", "night", "mid", ["text_sign", "lit"]),
 30: ("vegetation", "day", "mid", ["building"]),
 31: ("signage", "night", "close", ["text_sign", "neon"]),
 32: ("vegetation", "day", "tele_far", []),
 33: ("vegetation", "day", "tele_far", []),
 34: ("city_far", "day", "tele_far", ["mountain", "haze"]),
 35: ("vegetation", "day", "mid", []),
 36: ("building", "day", "mid", ["text_sign", "storefront"]),
 37: ("city_far", "night", "tele_far", ["text_sign"]),
 38: ("street", "day", "close", ["person", "storefront", "text_sign"]),
 39: ("building", "day", "mid", ["heritage", "vegetation"]),
 40: ("object", "day", "close", ["statue"]),
 41: ("vegetation", "day", "close", ["flower"]),
 42: ("vegetation", "day", "close", ["flower"]),
 43: ("vegetation", "day", "close", ["flower"]),
 44: ("vegetation", "day", "mid", []),
 45: ("building", "night", "mid", ["lit_facade"]),
 46: ("building", "night", "close", ["lit_facade"]),
 47: ("building", "night", "mid", ["text_sign", "lit"]),
 48: ("building", "night", "mid", ["vegetation"]),
 49: ("city_far", "night", "tele_far", ["text_sign"]),
 50: ("street", "day", "mid", ["storefront", "blossom", "text_sign"]),
 51: ("vegetation", "day", "close", ["flower", "macro"]),
 52: ("vegetation", "day", "close", ["building"]),
 53: ("object", "day", "mid", ["sculpture", "storefront"]),
 54: ("vegetation", "day", "mid", []),
 55: ("building", "day", "mid", ["text_sign"]),
 56: ("signage", "day", "close", ["text_dense"]),
 57: ("vegetation", "day", "close", ["flower", "macro"]),
 58: ("vegetation", "day", "close", ["flower"]),
 59: ("vegetation", "day", "close", ["grass"]),
 60: ("vegetation", "day", "close", ["flower"]),
 61: ("vegetation", "day", "tele_far", ["water", "road"]),
 62: ("building", "day", "close", ["heritage"]),
 63: ("building", "day", "tele_far", ["heritage"]),
 64: ("city_far", "night", "tele_far", []),
 65: ("city_far", "night", "tele_far", []),
 66: ("city_far", "night", "tele_far", []),
 67: ("building", "night", "mid", ["text_sign", "lit"]),
 68: ("city_far", "night", "tele_far", ["text_sign"]),
 69: ("indoor", "night", "close", ["text_sign", "shop"]),
 70: ("signage", "night", "close", ["text_sign", "neon"]),
 71: ("object", "day", "close", ["heritage", "sky"]),
 72: ("object", "day", "mid", ["boat", "water"]),
 73: ("object", "day", "close", ["boat", "heritage"]),
 74: ("water", "day", "mid", ["specular", "backlit"]),
 75: ("water", "day", "close", ["specular", "backlit"]),
 76: ("building", "day", "mid", ["glass"]),
 77: ("water", "day", "close", ["flower", "pond"]),
 78: ("building", "day", "mid", ["vegetation"]),
 79: ("building", "day", "mid", ["text_sign"]),
 80: ("signage", "day", "close", ["text_sign", "poster"]),
 81: ("building", "day", "mid", ["sky"]),
 82: ("building", "day", "mid", ["sky"]),
 83: ("vegetation", "day", "close", ["flower", "sunlit"]),
 84: ("building", "day", "mid", ["text_sign", "vegetation"]),
 85: ("city_far", "day", "tele_far", ["haze"]),
 86: ("street", "day", "tele_far", ["vegetation", "road", "vehicle"]),
 87: ("signage", "day", "mid", ["text_sign", "vegetation", "backlit"]),
 88: ("building", "night", "mid", ["water", "boat", "lit_facade"]),
 89: ("building", "day", "mid", ["construction", "crane"]),
 90: ("building", "day", "close", ["facade"]),
 91: ("vegetation", "day", "mid", ["palm"]),
 92: ("city_far", "night", "tele_far", []),
 93: ("indoor", "day", "close", ["flower"]),
 94: ("vegetation", "day", "close", ["flower", "sunlit"]),
 95: ("indoor", "day", "close", ["flower", "macro"]),
 96: ("vegetation", "day", "mid", ["text_sign", "grass"]),
 97: ("building", "night", "mid", ["facade"]),
 98: ("building", "day", "mid", ["heritage", "text_sign"]),
 99: ("building", "day", "mid", ["heritage", "text_sign", "roof"]),
 100:("vegetation", "day", "close", ["macro", "bokeh"]),
}

VAL = {
 1: ("city_far", "day", "tele_far", ["water", "vegetation", "haze"]),
 2: ("building", "night", "mid", ["text_sign", "lit", "glass"]),
 3: ("city_far", "day", "tele_far", ["mountain", "residential"]),
}

# 同场景组（同一主体不同焦段/时间，目视判定）
SCENE_GROUPS = {
    "构筑工地脚手架": [6, 7],
    "牛了个牛/中式快餐 沿街立面": [8, 9, 23, 36],
    "太平洋保险大厦": [11, 14, 24, 25, 92],
    "中海地产工地塔吊": [21, 22, 26],
    "欧式古典立面(外滩式)": [10, 62],
    "政府大楼夜景": [45, 46],
    "浙商证券": [47, 55],
    "山顶俯瞰夜景全景": [64, 65, 66],
    "玻璃穹顶+水面": [74, 75],
    "游船/古建屋顶": [72, 73],
    "墙面月季": [83, 94],
    "夜景城市远眺(同批)": [1, 2, 3, 4],
}
